name = "Polytopes"
uuid = "8b29e807-5630-435b-ae59-0075a85ba2d7"
authors = ["Cédric Belmant"]
version = "0.1.0"

[deps]
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"

[compat]
julia = "1.5"
LightGraphs = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
